function catalog = options(displayCatalog)
%SPHINX.POST.OPTIONS Show the available post-production workflow.
%   CATALOG = SPHINX.POST.OPTIONS prints and returns import controls,
%   diagnostics, and output products supported by the post-production API.

if nargin < 1
    displayCatalog = true;
end

catalog.importOptions = table( ...
    ["Snapshots";"Derived";"VerifyOrder"], ...
    ["all";"true";"true"], ...
    ["All saved steps, explicit saved step numbers, or snapshot indices"; ...
     "Compute B, E, J, probability current, momentum, and Poynting flux"; ...
     "Prove imported fields round-trip through the solver ordering"], ...
    'VariableNames',{'Option','Default','Meaning'});
catalog.diagnostics = table( ...
    ["probability";"energy";"field_statistics"], ...
    ["Probability integral, norm amplitude, and relative drift"; ...
     "EM, QM, total energy, constituent terms, and relative drift"; ...
     "Minimum, maximum, and RMS histories for primary fields"], ...
    'VariableNames',{'Name','Creates'});
catalog.products = table( ...
    ["summary";"conservation";"energy_breakdown";"snapshot";"lineout";"movie";"workspace"], ...
    ["CSV table of time-dependent diagnostics"; ...
     "PNG probability and energy conservation figure"; ...
     "PNG electromagnetic and quantum energy component figure"; ...
     "PNG 2D slice of any available scalar field"; ...
     "PNG lineout through any available scalar field"; ...
     "MP4 2D-slice movie of any available scalar field"; ...
     "MAT file containing imported data and computed analysis"], ...
    'VariableNames',{'Name','Creates'});
catalog.fields = ["probability","psiR","psiI","Ax","Ay","Az", ...
    "Yx","Yy","Yz","Bx","By","Bz","Ex","Ey","Ez", ...
    "Jx","Jy","Jz","poyntingX","poyntingY","poyntingZ"]';

if displayCatalog
    fprintf('\nSPHINX POST-PRODUCTION OPTIONS\n')
    fprintf('==============================\n')
    fprintf('1. Import:  data = sphinx.post.importRun(runFolder);\n')
    fprintf('2. Analyze: analysis = sphinx.post.analyze(data);\n')
    fprintf('3. Create:  files = sphinx.post.produce(data,analysis,["summary","conservation"]);\n\n')
    disp(catalog.importOptions)
    disp(catalog.diagnostics)
    disp(catalog.products)
    fprintf('Run help sphinx.post.produce for field, slice, lineout, and movie controls.\n\n')
end

end
