function catalog = options(displayCatalog)
%SPHINX.OPTIONS Display and return the supported simulation choices.
%   CATALOG = SPHINX.OPTIONS() prints a plain-language catalog and returns
%   tables describing models, boundaries, resolution profiles, and editable
%   name-value parameters for SPHINX.CONFIGURE.
%
%   CATALOG = SPHINX.OPTIONS(FALSE) returns the catalog without printing.

if nargin < 1
    displayCatalog = true;
end

catalog.models = table( ...
    ["EM";"QM";"both"], ...
    ["Electromagnetic fields evolve; the wavefunction is held fixed."; ...
     "The wavefunction evolves; electromagnetic fields are held fixed."; ...
     "The coupled Schrodinger-Maxwell system evolves."], ...
    'VariableNames',{'Option','Meaning'});

catalog.boundaries = table( ...
    ["fixed";"periodic"], ...
    ["Original fixed-boundary operator. Supported for square 2D grids only."; ...
     "Periodic derivative operators. Supported in 1D, 2D, and 3D."], ...
    'VariableNames',{'Option','Meaning'});

catalog.resolutions = table( ...
    ["quick";"standard";"original";"3d_demo"], ...
    ["31 x 31 x 1";"101 x 101 x 1";"251 x 251 x 1";"9 x 9 x 9"], ...
    [31;501;35001;11], ...
    ["Validated unit-scale setup for learning the interface."; ...
     "Moderate 2D exploratory calculation."; ...
     "Prime cyclotron configuration; preview before running."; ...
     "Small periodic 3D demonstration with unit-scale q and hbar."], ...
    'VariableNames',{'Option','Grid','TimePoints','Purpose'});

catalog.parameters = table( ...
    ["Model";"Boundary";"Resolution";"Grid";"ExtentLambda"; ...
     "Charge";"Mass";"Hbar";"SpeedOfLight";"Permittivity"; ...
     "ParticleNumber";"MagneticField";"Cycles";"EndTime";"TimePoints"; ...
     "SaveEvery";"RunName";"OutputRoot";"WriteManifest"], ...
    ["Subsystem evolution mode.";"Spatial boundary implementation."; ...
     "Convenience grid/time profile.";"Point counts [Nx,Ny,Nz]."; ...
     "Three [min,max] rows in units of lambda.";"Particle charge."; ...
     "Particle mass.";"Reduced Planck parameter.";"Speed-of-light parameter."; ...
     "Permittivity parameter.";"Particle-number normalization."; ...
     "Uniform magnetic-field scale for the cyclotron initializer."; ...
     "Cyclotron periods when EndTime is empty.";"Explicit physical final time."; ...
     "Total time points including the initial state."; ...
     "Integration steps between saved snapshots.";"Output run-family name."; ...
     "Parent output directory.";"Write JSON provenance and results."], ...
    'VariableNames',{'Name','Meaning'});

if displayCatalog
    fprintf('\nSPHINX SIMULATION OPTIONS\n')
    fprintf('=========================\n\n')
    fprintf('Models\n------\n')
    disp(catalog.models)
    fprintf('Boundaries\n----------\n')
    disp(catalog.boundaries)
    fprintf('Resolution profiles\n-------------------\n')
    disp(catalog.resolutions)
    fprintf('Configuration names\n-------------------\n')
    disp(catalog.parameters)
    fprintf('Example\n-------\n')
    fprintf('sim = sphinx.configure("cyclotron", "Resolution","quick", "Model","both");\n')
    fprintf('sphinx.describe(sim);\n')
    fprintf('result = sphinx.run(sim);\n\n')
end

end
